### PR TITLE
Format all with latest rustfmt (e1a0d82 2017-08-10)

### PR DESCRIPTION
**Pull request by CAD97**
$ rustup run nightly rustfmt --version
0.2.1-nightly (e1a0d82 2017-08-10)

Also manually fixed the too long line in the macro code.

### CODE REVIEW

**Comment by CAD97** [comment]
bors: r? @behnam

**Comment by behnam** [comment]
Looks good!

bors: r+

**Comment by behnam** [comment]
Yeah, I think bors-ng (the GH bors app) doesn't support `r?` and relies on GH access, etc.

**Comment by notriddle** [comment]
Neither bors nor homu accept `r?`. On rust-lang and servo repos, a separate bot called highfive does that.

**Comment by notriddle** [comment]
Or were you trying to do `bors delegate=behnam`?

**Comment by behnam** [comment]
Thanks, @notriddle, for the tips. From the docs (<https://bors.tech/getting-started/>), I thought that `delegate` is a matter of *permission* of reviewing, but not asking/assigning the review.

Anyway, if `bors delegate=<some-reviewer>` works without any permission needed, that can solve some of the assignment issues GH has, with non-collaborators being vary limited in setting assignee/reviewer fields.

**Comment by notriddle** [comment]
It is a matter of permission. I wasn't sure what you were trying to do, but with the :+1: you put on the post about highfive, you were asking about "requesting a review," not "give such-and-such permission to review."

I've been thinking to start factoring out generic "GitHub App API" stuff from bors-ng and build something kinda like highfive, but reaching and surpassing homu takes priority. Also, [probot] is probably advanced enough to do the jobs highfive currently does, so it's a matter of "is Elixir better enough than Node.JS to be worth it for something as low-importance as assigning reviewers and posting introductory messages?"

[probot]: https://github.com/probot

**Pull request merged**
