### PR TITLE
[char_property] Create module dir and add submodules

### PR DESCRIPTION
**Pull request by behnam**
Put the contract traits and macro all next to each other under one
module dir.

Also update some documentations.

### CODE REVIEW

**Comment by behnam** [comment]
bors: r? @CAD97

**Comment by CAD97** [comment]
bors: r+

**Comment by CAD97** [comment]
(I don't think I have permission in bors (whether I should or not is a different question), but I wanted to try)

**Comment by behnam** [comment]
> (I don't think I have permission in bors (whether I should or not is a different question), but I wanted to try)

*Now* you have! :)

**Comment by behnam** [comment]
bors: r+

**Comment by behnam** [comment]
bors: r+

**Comment by notriddle** [comment]
@behnam Why do you have both [bors] and [bors-voyager] enabled on the same repo?

[bors]: https://github.com/apps/bors
[bors-voyager]: https://github.com/apps/bors-voyager

**Comment by behnam** [comment]
That was a mistake, coming out of my explorations. Dropped @bors-voyager access already.

Btw, thanks for the great work with borg-ng, @notriddle! It's helping us a lot already!

**Pull request merged**
